Journal chap 1-3
friends-library/john-burnyeat pull request #8
Opened 2019-03-22 01:21 UTC by juliegugge

@jaredh159 @Henderjay

2019-03-22 10:05 UTC, juliegugge commented
Morning you guys.... I hope you have a good day today... Just wanted to tell you that at one point in fixing the typos I noticed that several lines were "gone" from the modern version -- in chapter one, the long paragraph that starts with When we were thus in our deep fears: the sentences : "and great dread and trembling fell upon us.... etc"... I don't know if I bumped something by accident or what... I went to the original version and copy/pasted the missing section and then corrected any typos, and I think I took care of it but I thought I'd tell you in case the PR version shows something missing... Also, there are a few letters that need formatting -- they don't match the rest of the letters... I tried to insert [.salutation] etc to see if it would change it and it didn't look like it did anything so I put it back.... True confessions... sigh.... I was also just a tad shy to insert these comments to you in the text, hence the comment here.... thanks

2019-03-22 14:52 UTC, Henderjay requested changes
Great work Julie. I left a few comments on a couple little things that need to be changed.  About the missing chunks in the beginning of the modernized version... I think it must have been because I edited that part for the _Truth in the Inward Parts_ book, and forgot that I had done it. :(  I'm not sure how many chunks are missing. If you think you can easily find them and put them back in, that would be great. If that sounds like a pain, we can put it on the list for another time. Thanks!!

2019-03-22 14:52 UTC, Henderjay commented on journal-letters/modernized/03-chapter-1.adoc
> +But, alas--we had not boldness,--for the living faith was lacking;
I think we want to leave the exclamation point in, and _then_ add the double dash.  Like: `But, alas!--we had`

2019-03-22 14:52 UTC, Henderjay commented on journal-letters/modernized/03-chapter-1.adoc
> +John 14:16 and 16:26. This Comforter being come and received,
Here he actually means John 14: verses 16 and 26. But you were right to add the period after the 26.

2019-03-22 14:52 UTC, Henderjay commented on journal-letters/modernized/03-chapter-1.adoc
> +O--the joy, the pleasure, and the great delight,
Here again lets keep the exclamation point. `O!--the joy,`

2019-03-22 14:52 UTC, Henderjay commented on journal-letters/modernized/03-chapter-1.adoc
> +Isa.1 and Isa. 66:3, where the Lord told Judah, their killing an ox,
This is right, but I think we just need a space between Isa. and 1 (like there is a space between Isa. and 63)

2019-03-22 14:52 UTC, Henderjay commented on journal-letters/modernized/04-chapter-2.adoc
> +O--the pleasant drawing near, and that not unprepared,
Same here... leave in the ! before the dashes (like you did a few lines up in line 40)

2019-03-22 19:31 UTC, juliegugge commented
ok... all done...

2019-03-25 20:43 UTC, merged

2019-03-25 20:43 UTC, Henderjay commented
looks good Julie, Merged.